import { Locale, locales } from '@/config/i18n/i18n';
import { cn } from '@/lib/utils';
import type { Metadata } from 'next';
import { NextIntlClientProvider, useMessages, useNow, useTimeZone } from 'next-intl';
import { unstable_setRequestLocale } from 'next-intl/server';
import { Poppins } from 'next/font/google';

export function generateStaticParams() {
  return locales.map((locale) => ({
    locale,
  }));
}

export type LocaleParamPageProps = {
  params: {
    locale: Locale;
  };
};

const inter = Poppins({ subsets: ['latin'], weight: ['400', '500', '600', '700'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function LocaleLayout({
  children,
  params,
}: {
  children: React.ReactNode;
} & LocaleParamPageProps) {
  unstable_setRequestLocale(params.locale);
  const messages = useMessages();
  const now = useNow();
  const timezone = useTimeZone();
  return (
    <html lang={params.locale}>
      <body className={cn('min-h-screen bg-background text-base text-foreground antialiased', inter.className)}>
        <NextIntlClientProvider locale={params.locale} messages={messages} now={now} timeZone={timezone}>
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
